name="trial_design"
list=["case control",
"cohort",
"cross-sectional",
"crossover",
"double-blind",
"epidemiological",
"multicentre",
"observational",
"open",
"parallel",
"postmarketing surveillance",
"prospective",
"randomised",
"retrospective",
"sequential",
"single-blind",]

name="Indications"
list=[
"Anaesthesia",
"Behaviour and behaviour mechanisms",
"Benign tumours",
"Biliary cancer",
"Bone cancer",
"Breast cancer",
"CNS cancer",
"Cancer metastases",
"Cardiovascular disorders",
"Colorectal cancer",
"Congenital disorders",
"Connective and soft tissue neoplasms",
"Connective tissue disorders",
"Connective tissue neoplasms",
"Cysts",
"Diabetes mellitus",
"Diabetic complications",
"Digestive system disorders",
"Drug toxicity",
"Ear nose and throat disorders",
"Endocrine disorders",
"Eye disorders",
"Eye neoplasms",
"Female urogenital diseases and pregnancy complications",
"Gastrointestinal cancer",
"Genitourinary disorders",
"Germ cell and embryonal neoplasms",
"Glandular and epithelial neoplasms",
"Haematological disorders",
"Haematological malignancies",
"Haemoblastosis",
"Hair disorders",
"Head and neck cancer",
"Heart disorders",
"Hereditary neoplastic syndromes",
"Immunological disorders",
"Inborn genetic disorders",
"Infections",
"Liver cancer",
"Liver disorders",
"Lung cancer",
"Lymphatic disorders",
"Male genital diseases",
"Male urogenital diseases",
"Malignant thymoma",
"Mental disorders",
"Mesothelioma",
"Metabolic disorders",
"Mouth disorders",
"Multisystem disorders",
"Musculoskeletal disorders",
"Nerve tissue neoplasms",
"Neuroendocrine carcinoma",
"Neuroendocrine tumours",
"Neurologic manifestations",
"Neurological disorders",
"Neuromuscular blockade",
"Neuromuscular disorders",
"Nevi and melanomas",
"Nutrition disorders",
"Pancreatic cancer",
"Pathologic processes",
"Pathological conditions| anatomical",
"Pathology and biological functions",
"Pelvic cancer",
"Peripheral nervous system neoplasms",
"Peritoneal cancer",
"Pigmentation",
"Plasmacytoma",
"Precancerous conditions",
"Respiration disorders",
"Respiratory hypersensitivity",
"Respiratory tract disorders",
"Respiratory tract infections",
"Sarcoma",
"Sclerosis",
"Sedation",
"Signs and symptoms",
"Signs symptoms and ill-defined conditions",
"Skin and soft tissue infections",
"Skin cancer",
"Skin disorders",
"Solid tumours",
"Squamous cell cancer",
"Stem cell mobilisation",
"Substance-related disorders",
"Thyroid cancer",
"Urogenital abnormalities",
"Urogenital cancer",
"Vascular disorders",
"Wounds and injuries",
]

name="mechanism_of_action"

list=[
"Alkylating agents",
"Amino acid modulators",
"Antacids",
"Antimetabolites",
"Antioxidants",
"Binding agents",
"Biological factor modulators",
"Biological transport modulators",
"Blood physiology modulators",
"Bone development modulators",
"Carbohydrate metabolism modulators",
"Cell modulators",
"Cell physiology modulators",
"Cell replacements",
"Central nervous system modulators",
"Chemical modulators",
"Cholesterol absorption inhibitors",
"Cholesterol synthesis inhibitors",
"Cytokine inhibitors",
"Cytokine modulators",
"Cytokine stimulants",
"Diagnostic imaging enhancers",
"Diuretics",
"Enzyme modulators",
"Enzyme replacements",
"Gene transference",
"Genetic process modulators",
"Genetic structure modulators",
"Glycopeptide modulators",
"Glycoprotein modulators",
"Growth substance modulators",
"Haemic and immune system modulators",
"Hormone modulators",
"Hormone replacements",
"Immunologic cytotoxicity",
"Inorganic chemical modulators",
"Inorganic chemical replacements",
"Ion channel agonists",
"Ion channel antagonists",
"Ion channel modulators",
"Ionising radiation emitters",
"Lipid modulators",
"Macromolecular substance inhibitors",
"Macromolecular substance stimulants",
"Membrane glycoprotein modulators",
"Metabolism-modulators",
"Microbiome modulators",
"Multiprotein complex modulators",
"Nervous system modulators",
"Neuromuscular blocking agents",
"Neurotransmitter agents",
"Neurotransmitter modulators",
"Nitric oxide donors",
"Nucleic acid nucleotide and nucleoside modulators",
"Ovarian follicle modulators",
"Peptide hormone modulators",
"Peptide modulators",
"Peptide replacements",
"Photosensitisers",
"Platelet aggregation modulators",
"Polymer modulators",
"Polysaccharide inhibitors",
"Polysaccharide modulators",
"Protein modulators",
"Protein replacements",
"Receptor inverse agonists",
"Scavengers",
"Signal transduction pathway modulators",
"Steroid modulators",
"Testosterone replacements",
"Tissue replacements",
"Undefined mechanism",
"Vascular disrupting agents",
"Virus internalisation modulators",
"Virus replication modulators",
"Vitamin modulators",
]
name="Drug class"
list=[
"Abortifacients",
"Adjuvants",
"Anabolic steroids",
"Anaesthetics",
"Anti-infectives",
"Anti-inflammatories",
"Antiallergics",
"Antiasthmatics",
"Antibronchitics",
"Anticoagulants",
"Antidiarrhoeals",
"Antidotes",
"Antifibrotics",
"Antihistamines",
"Antihormones",
"Antihypercalcaemics",
"Antihyperglycaemics",
"Antihypoglycaemics",
"Antineoplastics",
"Antipruritics",
"Antipyretics",
"Antirheumatics",
"Antisecretories",
"Antispasmodics",
"Antispastics",
"Antitussives",
"Antiulcers",
"Bronchodilators",
"Calcium regulators",
"Calcium supplements",
"Cardiovascular therapies",
"Chemopreventatives",
"Chemoprotectants",
"Chemosensitisers",
"Choleretics",
"Coagulants",
"Cytoprotectives",
"Decongestants",
"Digestion aids",
"Drug withdrawal therapies",
"Erectile dysfunction therapies",
"Expectorants",
"Eye disorder therapies",
"Foot disorder therapies",
"Gallstone therapies",
"Gastrokinetics",
"Hepatoprotectants",
"Hormonal replacements",
"Hyperphosphataemia therapies",
"Immunotherapies",
"Infertility therapies",
"Insulin sensitisers",
"Irritable bowel syndrome therapies",
"Laxatives",
"Mucolytics",
"Muscle relaxants",
"Neuroprotectants",
"Neuropsychotherapeutics",
"Obesity therapies",
"Osteoporosis therapies",
"Oxytocics",
"Phytotherapies",
"Probiotics",
"Radioprotectives",
"Radiosensitisers",
"Sclerosants",
"Skin disorder therapies",
"Surfactants",
"Tocolytics",
"Traditional medicines",
"Uricosurics",
"Urologics",
"Uroprotectives",
]

name="Therapeutic Area"
list=[
"Dermatology",
"Cardiovascular",
"Oncology",
"Rare Diseases",
"Psychiatry",
"Psychology",
"Hepatology",
"Endocrinology & Metabolic Diseases",
"ENT",
"Infectious Diseases",
"Respiratory",
"Neurology",
"Urology",
"Men's Health",
"Women's Health",
"Haematology",
"Soft & Connective Tissue",
"Ophthalmology",
"Internal Medicine",
"Musculoskeletal",
"Surgery",
"Pain & Analgesia",
"Toxicology & Poisoning",
"Immunology",
"Accident & Emergency",
"Obstetrics and Gynaecology",
"Nutrition & Weight Loss",
"Tissue & Regenerative Medicine",
"Others",
"Gastroenterology",
"Orthopedic",
"Nephrology",


]


for i in range(0,len(list)):
    # print(f"""<input  class="toggle" hidden  name="{name}" id="{list[i]}" type="checkbox" ><label for="{list[i]}" class="btn"><span>{i}</span>{list[i]}</label>""")
    print(f"""<input id="{list[i]}" class ="toggle toggle-left" name="{name}" value="{list[i]}" type="radio" ><label for="{list[i]}" class ="btn" > <span> {i} </span> {list[i]} </label>""")
